language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - npm run docs
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run coveralls
    on:
      condition: $TRAVIS_BRANCH =~ ^(main|v[0-9]+\.[0-9]+\.[0-9]+)$
      all_branches: true
  - provider: npm
    skip_cleanup: true
    email: chris@topher.land
    api_key: $NPM_API_TOKEN
    on:
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
      all_branches: true
  - provider: npm
    skip_cleanup: true
    tag: prerelease
    email: chris@topher.land
    api_key: $NPM_API_TOKEN
    on:
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[^[:space:]]+$
      all_branches: true
  - provider: pages
    skip_cleanup: true
    keep_history: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    on:
      condition: $TRAVIS_BRANCH =~ ^(main|v[0-9]+\.[0-9]+\.[0-9]+)$
      all_branches: true
